name: 'Increment'
description: 'This action increments a digit in the specified file.'
inputs:
  file-path:
    description: 'File containing the digit to increment'
    required: false
    default: 'app.json'
  pattern:
    description: 'RegExp pattern'
    required: false
    default: '"versionCode": (\d+)'
  flags:
    description: 'RegExp flag string'
    required: false
    default: 'g'
runs:
  using: 'node16'
  main: 'index.js'
