name: Main CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  test:
    name: Test increment action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create test file
        run: |
          echo "{\n\t\"versionCode\": 2,\n\t\"someOtherProperty\": 3\n}" > app.json

      - name: Run increment action
        uses: jb-0/increment-action@main

      - name: Print test file
        run: |
          printf '%b\n' "$(cat app.json)"
