name: Main CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  test:
    name: Test increment action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create test file
        run: |
          echo "{\n\t\"versionCode\": 2,\n\t\"someOtherProperty\": 3\n}" > app.json

      - name: Run increment action
        uses: jb-0/increment-action@v0.1.2

      - name: Print test file
        run: |
          printf '%b\n' "$(cat app.json)"
